[2019-03-21 17:28:36 *68996.2]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=5] is closed.
[2019-03-21 17:28:36 *68996.2]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=13] is closed.
[2019-03-21 17:28:36 *68996.2]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=21] is closed.
[2019-03-21 17:28:36 *68996.2]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=29] is closed.
[2019-03-21 17:28:36 *68996.2]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=37] is closed.
[2019-03-21 17:28:36 *68996.2]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=45] is closed.
[2019-03-21 17:28:36 *68996.2]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=53] is closed.
[2019-03-21 17:28:36 *68996.2]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=85] is closed.
[2019-03-21 17:28:36 *68996.2]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=61] is closed.
[2019-03-21 17:28:36 *68996.2]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=69] is closed.
[2019-03-21 17:28:36 *68996.2]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=93] is closed.
[2019-03-21 17:28:36 *68996.2]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=77] is closed.
[2019-03-21 17:28:36 *68996.2]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=101] is closed.
[2019-03-21 17:28:36 *68996.2]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=109] is closed.
[2019-03-21 17:28:36 *68996.2]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=117] is closed.
[2019-03-21 17:28:36 *68996.2]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=125] is closed.
[2019-03-21 17:28:36 *68996.2]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=133] is closed.
[2019-03-21 17:28:36 *68996.2]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=141] is closed.
[2019-03-21 17:28:36 *68999.5]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=8] is closed.
[2019-03-21 17:28:36 *68996.2]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=149] is closed.
[2019-03-21 17:28:36 *68999.5]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=16] is closed.
[2019-03-21 17:28:36 *68996.2]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=157] is closed.
[2019-03-21 17:28:36 *68996.2]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=165] is closed.
[2019-03-21 17:28:36 *68999.5]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=24] is closed.
[2019-03-21 17:28:36 *68999.5]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=32] is closed.
[2019-03-21 17:28:36 *68996.2]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=173] is closed.
[2019-03-21 17:28:36 *68999.5]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=40] is closed.
[2019-03-21 17:28:36 *68996.2]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=181] is closed.
[2019-03-21 17:28:36 *68999.5]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=48] is closed.
[2019-03-21 17:28:36 *68996.2]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=189] is closed.
[2019-03-21 17:28:36 *68999.5]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=56] is closed.
[2019-03-21 17:28:36 *68996.2]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=197] is closed.
[2019-03-21 17:28:36 *68999.5]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=80] is closed.
[2019-03-21 17:28:36 *68999.5]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=64] is closed.
[2019-03-21 17:28:36 *68998.4]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=15] is closed.
[2019-03-21 17:28:36 *68998.4]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=7] is closed.
[2019-03-21 17:28:36 *68998.4]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=23] is closed.
[2019-03-21 17:28:36 *68998.4]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=39] is closed.
[2019-03-21 17:28:36 *68995.1]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=4] is closed.
[2019-03-21 17:28:36 *68994.0]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=3] is closed.
[2019-03-21 17:28:36 *68994.0]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=11] is closed.
[2019-03-21 17:28:36 *68994.0]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=19] is closed.
[2019-03-21 17:28:36 *68994.0]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=27] is closed.
[2019-03-21 17:28:36 *68994.0]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=35] is closed.
[2019-03-21 17:28:36 *68994.0]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=43] is closed.
[2019-03-21 17:28:36 *68994.0]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=51] is closed.
[2019-03-21 17:28:36 *68994.0]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=59] is closed.
[2019-03-21 17:28:36 *68994.0]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=83] is closed.
[2019-03-21 17:28:36 *68994.0]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=91] is closed.
[2019-03-21 17:28:36 *68994.0]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=67] is closed.
[2019-03-21 17:28:36 *68994.0]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=75] is closed.
[2019-03-21 17:28:36 *68994.0]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=99] is closed.
[2019-03-21 17:28:36 *68994.0]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=107] is closed.
[2019-03-21 17:28:36 *68996.2]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=205] is closed.
[2019-03-21 17:28:36 *68998.4]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=95] is closed.
[2019-03-21 17:28:36 *68996.2]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=213] is closed.
[2019-03-21 17:28:36 *68999.5]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=112] is closed.
[2019-03-21 17:28:36 *68998.4]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=31] is closed.
[2019-03-21 17:28:36 *68999.5]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=88] is closed.
[2019-03-21 17:28:36 *68998.4]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=47] is closed.
[2019-03-21 17:28:36 *68996.2]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=221] is closed.
[2019-03-21 17:28:36 *68998.4]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=55] is closed.
[2019-03-21 17:28:36 *68995.1]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=12] is closed.
[2019-03-21 17:28:36 *68999.5]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=128] is closed.
[2019-03-21 17:28:36 *68998.4]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=63] is closed.
[2019-03-21 17:28:36 *68995.1]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=20] is closed.
[2019-03-21 17:28:36 *68999.5]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=72] is closed.
[2019-03-21 17:28:36 *68996.2]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=229] is closed.
[2019-03-21 17:28:36 *68998.4]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=71] is closed.
[2019-03-21 17:28:36 *68999.5]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=96] is closed.
[2019-03-21 17:28:36 *68995.1]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=36] is closed.
[2019-03-21 17:28:36 *68998.4]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=79] is closed.
[2019-03-21 17:28:36 *68996.2]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=237] is closed.
[2019-03-21 17:28:36 *68998.4]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=103] is closed.
[2019-03-21 17:28:36 *68995.1]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=28] is closed.
[2019-03-21 17:28:36 *68998.4]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=87] is closed.
[2019-03-21 17:28:36 *68999.5]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=136] is closed.
[2019-03-21 17:28:36 *68998.4]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=111] is closed.
[2019-03-21 17:28:36 *68995.1]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=44] is closed.
[2019-03-21 17:28:36 *68996.2]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=253] is closed.
[2019-03-21 17:28:36 *68999.5]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=104] is closed.
[2019-03-21 17:28:36 *68996.2]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=245] is closed.
[2019-03-21 17:28:36 *68998.4]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=119] is closed.
[2019-03-21 17:28:36 *68995.1]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=52] is closed.
[2019-03-21 17:28:36 *68995.1]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=76] is closed.
[2019-03-21 17:28:36 *68998.4]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=127] is closed.
[2019-03-21 17:28:36 *68999.5]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=120] is closed.
[2019-03-21 17:28:36 *68995.1]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=68] is closed.
[2019-03-21 17:28:36 *68998.4]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=135] is closed.
[2019-03-21 17:28:36 *68995.1]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=60] is closed.
[2019-03-21 17:28:36 *68996.2]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=269] is closed.
[2019-03-21 17:28:36 *68995.1]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=84] is closed.
[2019-03-21 17:28:36 *68998.4]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=143] is closed.
[2019-03-21 17:28:36 *68999.5]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=144] is closed.
[2019-03-21 17:28:36 *68996.2]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=261] is closed.
[2019-03-21 17:28:36 *68995.1]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=108] is closed.
[2019-03-21 17:28:36 *68998.4]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=151] is closed.
[2019-03-21 17:28:36 *68995.1]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=100] is closed.
[2019-03-21 17:28:36 *68996.2]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=285] is closed.
[2019-03-21 17:28:36 *68999.5]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=160] is closed.
[2019-03-21 17:28:36 *68995.1]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=92] is closed.
[2019-03-21 17:28:36 *68998.4]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=159] is closed.
[2019-03-21 17:28:36 *68999.5]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=152] is closed.
[2019-03-21 17:28:36 *68995.1]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=116] is closed.
[2019-03-21 17:28:36 *68996.2]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=277] is closed.
[2019-03-21 17:28:36 *68998.4]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=175] is closed.
[2019-03-21 17:28:36 *68998.4]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=167] is closed.
[2019-03-21 17:28:36 *68999.5]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=184] is closed.
[2019-03-21 17:28:36 *68998.4]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=183] is closed.
[2019-03-21 17:28:36 *68995.1]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=124] is closed.
[2019-03-21 17:28:36 *68998.4]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=199] is closed.
[2019-03-21 17:28:36 *68999.5]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=176] is closed.
[2019-03-21 17:28:36 *68995.1]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=132] is closed.
[2019-03-21 17:28:36 *68999.5]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=168] is closed.
[2019-03-21 17:28:36 *68996.2]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=293] is closed.
[2019-03-21 17:28:36 *68998.4]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=207] is closed.
[2019-03-21 17:28:36 *68995.1]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=140] is closed.
[2019-03-21 17:28:36 *68996.2]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=301] is closed.
[2019-03-21 17:28:36 *68998.4]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=191] is closed.
[2019-03-21 17:28:36 *68999.5]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=200] is closed.
[2019-03-21 17:28:36 *68998.4]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=215] is closed.
[2019-03-21 17:28:36 *68995.1]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=148] is closed.
[2019-03-21 17:28:36 *68996.2]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=317] is closed.
[2019-03-21 17:28:36 *68999.5]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=192] is closed.
[2019-03-21 17:28:36 *68996.2]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=309] is closed.
[2019-03-21 17:28:36 *68995.1]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=164] is closed.
[2019-03-21 17:28:36 *68998.4]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=223] is closed.
[2019-03-21 17:28:36 *68995.1]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=156] is closed.
[2019-03-21 17:28:36 *68998.4]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=247] is closed.
[2019-03-21 17:28:36 *68999.5]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=248] is closed.
[2019-03-21 17:28:36 *68995.1]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=172] is closed.
[2019-03-21 17:28:36 *68996.2]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=325] is closed.
[2019-03-21 17:28:36 *68998.4]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=231] is closed.
[2019-03-21 17:28:36 *68995.1]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=188] is closed.
[2019-03-21 17:28:36 *68999.5]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=216] is closed.
[2019-03-21 17:28:36 *68999.5]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=208] is closed.
[2019-03-21 17:28:36 *68995.1]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=180] is closed.
[2019-03-21 17:28:36 *68998.4]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=279] is closed.
[2019-03-21 17:28:36 *68996.2]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=333] is closed.
[2019-03-21 17:28:36 *68998.4]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=239] is closed.
[2019-03-21 17:28:36 *68995.1]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=196] is closed.
[2019-03-21 17:28:36 *68996.2]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=357] is closed.
[2019-03-21 17:28:36 *68998.4]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=255] is closed.
[2019-03-21 17:28:36 *68995.1]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=204] is closed.
[2019-03-21 17:28:36 *68999.5]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=232] is closed.
[2019-03-21 17:28:36 *68996.2]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=349] is closed.
[2019-03-21 17:28:36 *68998.4]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=263] is closed.
[2019-03-21 17:28:36 *68999.5]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=224] is closed.
[2019-03-21 17:28:36 *68996.2]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=341] is closed.
[2019-03-21 17:28:36 *68995.1]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=220] is closed.
[2019-03-21 17:28:36 *68996.2]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=365] is closed.
[2019-03-21 17:28:36 *68995.1]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=212] is closed.
[2019-03-21 17:28:36 *68998.4]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=271] is closed.
[2019-03-21 17:28:36 *68999.5]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=240] is closed.
[2019-03-21 17:28:36 *68995.1]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=228] is closed.
[2019-03-21 17:28:36 *68999.5]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=264] is closed.
[2019-03-21 17:28:36 *68998.4]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=295] is closed.
[2019-03-21 17:28:36 *68999.5]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=256] is closed.
[2019-03-21 17:28:36 *68995.1]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=244] is closed.
[2019-03-21 17:28:36 *68998.4]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=287] is closed.
[2019-03-21 17:28:36 *68995.1]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=236] is closed.
[2019-03-21 17:28:36 *68999.5]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=280] is closed.
[2019-03-21 17:28:36 *68998.4]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=303] is closed.
[2019-03-21 17:28:36 *68996.2]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=373] is closed.
[2019-03-21 17:28:36 *68998.4]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=319] is closed.
[2019-03-21 17:28:36 *68995.1]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=252] is closed.
[2019-03-21 17:28:36 *68999.5]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=272] is closed.
[2019-03-21 17:28:36 *68998.4]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=311] is closed.
[2019-03-21 17:28:36 *68995.1]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=260] is closed.
[2019-03-21 17:28:36 *68994.0]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=115] is closed.
[2019-03-21 17:28:36 *68997.3]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=6] is closed.
[2019-03-21 17:28:36 *68994.0]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=155] is closed.
[2019-03-21 17:28:36 *68997.3]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=14] is closed.
[2019-03-21 17:28:36 *68994.0]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=147] is closed.
[2019-03-21 17:28:36 *68997.3]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=22] is closed.
[2019-03-21 17:28:36 *68994.0]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=123] is closed.
[2019-03-21 17:28:36 *68997.3]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=30] is closed.
[2019-03-21 17:28:36 *68994.0]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=139] is closed.
[2019-03-21 17:28:36 *68997.3]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=38] is closed.
[2019-03-21 17:28:36 *68994.0]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=131] is closed.
[2019-03-21 17:28:36 *68997.3]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=46] is closed.
[2019-03-21 17:28:36 *68994.0]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=171] is closed.
[2019-03-21 17:28:36 *68997.3]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=54] is closed.
[2019-03-21 17:28:36 *68997.3]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=62] is closed.
[2019-03-21 17:28:36 *68997.3]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=86] is closed.
[2019-03-21 17:28:36 *68994.0]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=179] is closed.
[2019-03-21 17:28:36 *68997.3]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=70] is closed.
[2019-03-21 17:28:36 *68997.3]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=94] is closed.
[2019-03-21 17:28:36 *68994.0]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=187] is closed.
[2019-03-21 17:28:36 *69000.6]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=1] is closed.
[2019-03-21 17:28:36 *68997.3]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=78] is closed.
[2019-03-21 17:28:36 *68994.0]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=163] is closed.
[2019-03-21 17:28:36 *69000.6]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=17] is closed.
[2019-03-21 17:28:36 *68997.3]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=102] is closed.
[2019-03-21 17:28:37 *68997.3]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=110] is closed.
[2019-03-21 17:28:37 *69000.6]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=9] is closed.
[2019-03-21 17:28:37 *68997.3]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=118] is closed.
[2019-03-21 17:28:37 *69000.6]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=25] is closed.
[2019-03-21 17:28:37 *68994.0]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=195] is closed.
[2019-03-21 17:28:37 *69000.6]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=33] is closed.
[2019-03-21 17:28:37 *68997.3]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=126] is closed.
[2019-03-21 17:28:37 *68994.0]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=203] is closed.
[2019-03-21 17:28:37 *69000.6]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=41] is closed.
[2019-03-21 17:28:37 *68997.3]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=134] is closed.
[2019-03-21 17:28:37 *69000.6]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=49] is closed.
[2019-03-21 17:28:37 *68997.3]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=142] is closed.
[2019-03-21 17:28:37 *68994.0]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=211] is closed.
[2019-03-21 17:28:37 *69000.6]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=57] is closed.
[2019-03-21 17:28:37 *68997.3]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=150] is closed.
[2019-03-21 17:28:37 *69000.6]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=81] is closed.
[2019-03-21 17:28:37 *68994.0]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=219] is closed.
[2019-03-21 17:28:37 *68997.3]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=158] is closed.
[2019-03-21 17:28:37 *69000.6]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=65] is closed.
[2019-03-21 17:28:37 *68994.0]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=227] is closed.
[2019-03-21 17:28:37 *68997.3]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=166] is closed.
[2019-03-21 17:28:37 *69000.6]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=89] is closed.
[2019-03-21 17:28:37 *68994.0]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=235] is closed.
[2019-03-21 17:28:37 *69000.6]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=73] is closed.
[2019-03-21 17:28:37 *68994.0]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=251] is closed.
[2019-03-21 17:28:37 *68996.2]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=381] is closed.
[2019-03-21 17:28:37 *69001.7]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=2] is closed.
[2019-03-21 17:28:37 *68997.3]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=174] is closed.
[2019-03-21 17:28:37 *69000.6]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=97] is closed.
[2019-03-21 17:28:37 *68994.0]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=243] is closed.
[2019-03-21 17:28:37 *68996.2]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=405] is closed.
[2019-03-21 17:28:37 *68997.3]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=182] is closed.
[2019-03-21 17:28:37 *69001.7]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=10] is closed.
[2019-03-21 17:28:37 *69000.6]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=105] is closed.
[2019-03-21 17:28:37 *68997.3]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=190] is closed.
[2019-03-21 17:28:37 *68994.0]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=275] is closed.
[2019-03-21 17:28:37 *68996.2]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=397] is closed.
[2019-03-21 17:28:37 *69000.6]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=113] is closed.
[2019-03-21 17:28:37 *68994.0]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=259] is closed.
[2019-03-21 17:28:37 *68997.3]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=198] is closed.
[2019-03-21 17:28:37 *69000.6]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=121] is closed.
[2019-03-21 17:28:37 *68997.3]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=206] is closed.
[2019-03-21 17:28:37 *69000.6]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=129] is closed.
[2019-03-21 17:28:37 *69001.7]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=26] is closed.
[2019-03-21 17:28:37 *68994.0]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=307] is closed.
[2019-03-21 17:28:37 *68997.3]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=214] is closed.
[2019-03-21 17:28:37 *69000.6]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=137] is closed.
[2019-03-21 17:28:37 *68994.0]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=267] is closed.
[2019-03-21 17:28:37 *68997.3]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=222] is closed.
[2019-03-21 17:28:37 *69001.7]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=18] is closed.
[2019-03-21 17:28:37 *69000.6]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=145] is closed.
[2019-03-21 17:28:37 *68997.3]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=230] is closed.
[2019-03-21 17:28:37 *68994.0]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=315] is closed.
[2019-03-21 17:28:37 *69000.6]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=153] is closed.
[2019-03-21 17:28:37 *69001.7]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=58] is closed.
[2019-03-21 17:28:37 *68994.0]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=283] is closed.
[2019-03-21 17:28:37 *68997.3]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=238] is closed.
[2019-03-21 17:28:37 *69000.6]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=161] is closed.
[2019-03-21 17:28:37 *68994.0]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=291] is closed.
[2019-03-21 17:28:37 *68997.3]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=246] is closed.
[2019-03-21 17:28:37 *69001.7]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=50] is closed.
[2019-03-21 17:28:37 *68994.0]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=299] is closed.
[2019-03-21 17:28:37 *69000.6]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=169] is closed.
[2019-03-21 17:28:37 *68997.3]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=254] is closed.
[2019-03-21 17:28:37 *69001.7]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=42] is closed.
[2019-03-21 17:28:37 *68996.2]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=389] is closed.
[2019-03-21 17:28:37 *68994.0]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=323] is closed.
[2019-03-21 17:28:37 *69000.6]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=185] is closed.
[2019-03-21 17:28:37 *68997.3]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=262] is closed.
[2019-03-21 17:28:37 *69001.7]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=34] is closed.
[2019-03-21 17:28:37 *69000.6]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=177] is closed.
[2019-03-21 17:28:37 *68997.3]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=270] is closed.
[2019-03-21 17:28:37 *68997.3]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=278] is closed.
[2019-03-21 17:28:37 *68994.0]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=331] is closed.
[2019-03-21 17:28:37 *69000.6]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=193] is closed.
[2019-03-21 17:28:37 *68997.3]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=286] is closed.
[2019-03-21 17:28:37 *69000.6]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=201] is closed.
[2019-03-21 17:28:37 *68994.0]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=363] is closed.
[2019-03-21 17:28:37 *68997.3]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=294] is closed.
[2019-03-21 17:28:37 *69001.7]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=82] is closed.
[2019-03-21 17:28:37 *69000.6]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=209] is closed.
[2019-03-21 17:28:37 *68994.0]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=355] is closed.
[2019-03-21 17:28:37 *68997.3]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=302] is closed.
[2019-03-21 17:28:37 *69000.6]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=225] is closed.
[2019-03-21 17:28:37 *68999.5]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=296] is closed.
[2019-03-21 17:28:37 *68995.1]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=268] is closed.
[2019-03-21 17:28:37 *68996.2]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=421] is closed.
[2019-03-21 17:28:37 *68998.4]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=327] is closed.
[2019-03-21 17:28:37 *68996.2]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=437] is closed.
[2019-03-21 17:28:37 *68996.2]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=413] is closed.
[2019-03-21 17:28:37 *68999.5]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=288] is closed.
[2019-03-21 17:28:37 *68995.1]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=316] is closed.
[2019-03-21 17:28:37 *68998.4]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=335] is closed.
[2019-03-21 17:28:37 *68995.1]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=276] is closed.
[2019-03-21 17:28:37 *68999.5]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=304] is closed.
[2019-03-21 17:28:37 *68995.1]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=284] is closed.
[2019-03-21 17:28:37 *68999.5]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=312] is closed.
[2019-03-21 17:28:37 *68998.4]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=343] is closed.
[2019-03-21 17:28:37 *68999.5]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=320] is closed.
[2019-03-21 17:28:37 *68995.1]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=292] is closed.
[2019-03-21 17:28:37 *68998.4]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=375] is closed.
[2019-03-21 17:28:37 *68999.5]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=328] is closed.
[2019-03-21 17:28:37 *68998.4]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=351] is closed.
[2019-03-21 17:28:37 *68995.1]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=308] is closed.
[2019-03-21 17:28:37 *68999.5]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=336] is closed.
[2019-03-21 17:28:37 *68998.4]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=359] is closed.
[2019-03-21 17:28:37 *68999.5]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=344] is closed.
[2019-03-21 17:28:37 *68995.1]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=300] is closed.
[2019-03-21 17:28:37 *68999.5]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=352] is closed.
[2019-03-21 17:28:37 *68998.4]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=367] is closed.
[2019-03-21 17:28:37 *68999.5]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=360] is closed.
[2019-03-21 17:28:37 *68995.1]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=324] is closed.
[2019-03-21 17:28:37 *68999.5]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=368] is closed.
[2019-03-21 17:28:37 *68998.4]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=399] is closed.
[2019-03-21 17:28:37 *68995.1]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=348] is closed.
[2019-03-21 17:28:37 *68999.5]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=376] is closed.
[2019-03-21 17:28:37 *69001.7]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=98] is closed.
[2019-03-21 17:28:37 *68998.4]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=383] is closed.
[2019-03-21 17:28:37 *68995.1]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=340] is closed.
[2019-03-21 17:28:37 *68999.5]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=384] is closed.
[2019-03-21 17:28:37 *68995.1]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=332] is closed.
[2019-03-21 17:28:37 *68998.4]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=391] is closed.
[2019-03-21 17:28:37 *68999.5]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=392] is closed.
[2019-03-21 17:28:37 *68998.4]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=415] is closed.
[2019-03-21 17:28:37 *68999.5]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=400] is closed.
[2019-03-21 17:28:37 *68999.5]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=408] is closed.
[2019-03-21 17:28:37 *68995.1]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=372] is closed.
[2019-03-21 17:28:37 *68998.4]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=423] is closed.
[2019-03-21 17:28:37 *68999.5]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=416] is closed.
[2019-03-21 17:28:37 *68999.5]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=424] is closed.
[2019-03-21 17:28:37 *68998.4]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=439] is closed.
[2019-03-21 17:28:37 *69001.7]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=74] is closed.
[2019-03-21 17:28:37 *68995.1]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=356] is closed.
[2019-03-21 17:28:37 *68995.1]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=364] is closed.
[2019-03-21 17:28:37 *68998.4]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=407] is closed.
[2019-03-21 17:28:37 *69001.7]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=66] is closed.
[2019-03-21 17:28:37 *68995.1]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=380] is closed.
[2019-03-21 17:28:37 *69001.7]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=90] is closed.
[2019-03-21 17:28:37 *68995.1]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=388] is closed.
[2019-03-21 17:28:37 *68995.1]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=396] is closed.
[2019-03-21 17:28:37 *68995.1]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=420] is closed.
[2019-03-21 17:28:37 *68995.1]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=404] is closed.
[2019-03-21 17:28:37 *69001.7]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=106] is closed.
[2019-03-21 17:28:37 *68995.1]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=412] is closed.
[2019-03-21 17:28:37 *69001.7]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=130] is closed.
[2019-03-21 17:28:37 *68995.1]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=436] is closed.
[2019-03-21 17:28:37 *69001.7]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=122] is closed.
[2019-03-21 17:28:37 *68994.0]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=339] is closed.
[2019-03-21 17:28:37 *69001.7]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=114] is closed.
[2019-03-21 17:28:37 *68994.0]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=347] is closed.
[2019-03-21 17:28:37 *69000.6]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=217] is closed.
[2019-03-21 17:28:37 *68997.3]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=310] is closed.
[2019-03-21 17:28:37 *69001.7]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=170] is closed.
[2019-03-21 17:28:37 *68994.0]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=371] is closed.
[2019-03-21 17:28:37 *69000.6]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=241] is closed.
[2019-03-21 17:28:37 *69000.6]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=233] is closed.
[2019-03-21 17:28:37 *69001.7]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=138] is closed.
[2019-03-21 17:28:37 *68994.0]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=387] is closed.
[2019-03-21 17:28:37 *68997.3]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=350] is closed.
[2019-03-21 17:28:37 *68994.0]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=379] is closed.
[2019-03-21 17:28:37 *69000.6]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=249] is closed.
[2019-03-21 17:28:37 *69001.7]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=146] is closed.
[2019-03-21 17:28:37 *68997.3]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=318] is closed.
[2019-03-21 17:28:37 *68994.0]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=395] is closed.
[2019-03-21 17:28:37 *69000.6]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=257] is closed.
[2019-03-21 17:28:37 *69001.7]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=178] is closed.
[2019-03-21 17:28:37 *68994.0]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=403] is closed.
[2019-03-21 17:28:37 *69001.7]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=162] is closed.
[2019-03-21 17:28:37 *69000.6]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=273] is closed.
[2019-03-21 17:28:37 *68997.3]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=342] is closed.
[2019-03-21 17:28:37 *69000.6]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=265] is closed.
[2019-03-21 17:28:37 *68994.0]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=411] is closed.
[2019-03-21 17:28:37 *69000.6]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=281] is closed.
[2019-03-21 17:28:37 *69001.7]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=194] is closed.
[2019-03-21 17:28:37 *69001.7]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=154] is closed.
[2019-03-21 17:28:37 *68994.0]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=419] is closed.
[2019-03-21 17:28:37 *68997.3]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=334] is closed.
[2019-03-21 17:28:37 *69000.6]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=305] is closed.
[2019-03-21 17:28:37 *68997.3]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=326] is closed.
[2019-03-21 17:28:37 *68994.0]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=435] is closed.
[2019-03-21 17:28:37 *69000.6]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=297] is closed.
[2019-03-21 17:28:37 *68994.0]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=427] is closed.
[2019-03-21 17:28:37 *69001.7]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=202] is closed.
[2019-03-21 17:28:37 *69000.6]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=289] is closed.
[2019-03-21 17:28:37 *69001.7]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=186] is closed.
[2019-03-21 17:28:37 *68994.0]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=443] is closed.
[2019-03-21 17:28:37 *69000.6]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=353] is closed.
[2019-03-21 17:28:37 *69000.6]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=313] is closed.
[2019-03-21 17:28:37 *69000.6]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=329] is closed.
[2019-03-21 17:28:37 *69001.7]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=210] is closed.
[2019-03-21 17:28:37 *69000.6]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=321] is closed.
[2019-03-21 17:28:37 *68997.3]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=390] is closed.
[2019-03-21 17:28:37 *69001.7]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=218] is closed.
[2019-03-21 17:28:37 *69000.6]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=345] is closed.
[2019-03-21 17:28:37 *69000.6]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=337] is closed.
[2019-03-21 17:28:37 *69001.7]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=226] is closed.
[2019-03-21 17:28:37 *68997.3]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=382] is closed.
[2019-03-21 17:28:37 *69001.7]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=234] is closed.
[2019-03-21 17:28:37 *69000.6]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=361] is closed.
[2019-03-21 17:28:37 *68997.3]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=374] is closed.
[2019-03-21 17:28:37 *69001.7]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=242] is closed.
[2019-03-21 17:28:37 *69001.7]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=266] is closed.
[2019-03-21 17:28:37 *68997.3]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=366] is closed.
[2019-03-21 17:28:37 *69000.6]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=369] is closed.
[2019-03-21 17:28:37 *69000.6]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=377] is closed.
[2019-03-21 17:28:37 *69000.6]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=393] is closed.
[2019-03-21 17:28:37 *69001.7]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=298] is closed.
[2019-03-21 17:28:37 *68997.3]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=358] is closed.
[2019-03-21 17:28:37 *69001.7]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=274] is closed.
[2019-03-21 17:28:37 *69000.6]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=385] is closed.
[2019-03-21 17:28:37 *69000.6]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=401] is closed.
[2019-03-21 17:28:37 *68997.3]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=406] is closed.
[2019-03-21 17:28:37 *69001.7]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=250] is closed.
[2019-03-21 17:28:37 *69001.7]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=282] is closed.
[2019-03-21 17:28:37 *69000.6]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=417] is closed.
[2019-03-21 17:28:37 *69000.6]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=409] is closed.
[2019-03-21 17:28:37 *69001.7]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=314] is closed.
[2019-03-21 17:28:37 *69001.7]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=258] is closed.
[2019-03-21 17:28:37 *68997.3]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=422] is closed.
[2019-03-21 17:28:37 *69001.7]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=290] is closed.
[2019-03-21 17:28:37 *69000.6]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=425] is closed.
[2019-03-21 17:28:37 *69001.7]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=306] is closed.
[2019-03-21 17:28:37 *68997.3]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=398] is closed.
[2019-03-21 17:28:37 *69000.6]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=433] is closed.
[2019-03-21 17:28:37 *68997.3]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=414] is closed.
[2019-03-21 17:28:37 *69000.6]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=441] is closed.
[2019-03-21 17:28:37 *69000.6]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=457] is closed.
[2019-03-21 17:28:37 *69000.6]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=449] is closed.
[2019-03-21 17:28:37 *68997.3]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=462] is closed.
[2019-03-21 17:28:37 *69001.7]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=322] is closed.
[2019-03-21 17:28:37 *68997.3]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=430] is closed.
[2019-03-21 17:28:37 *69001.7]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=330] is closed.
[2019-03-21 17:28:37 *69000.6]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=465] is closed.
[2019-03-21 17:28:37 *69001.7]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=370] is closed.
[2019-03-21 17:28:37 *69001.7]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=338] is closed.
[2019-03-21 17:28:37 *68997.3]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=446] is closed.
[2019-03-21 17:28:37 *68997.3]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=438] is closed.
[2019-03-21 17:28:37 *68997.3]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=454] is closed.
[2019-03-21 17:28:37 *68997.3]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=470] is closed.
[2019-03-21 17:28:37 *69001.7]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=346] is closed.
[2019-03-21 17:28:37 *69001.7]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=362] is closed.
[2019-03-21 17:28:37 *69001.7]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=354] is closed.
[2019-03-21 17:28:37 *69001.7]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=386] is closed.
[2019-03-21 17:28:37 *69001.7]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=378] is closed.
[2019-03-21 17:28:37 *69000.6]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=481] is closed.
[2019-03-21 17:28:37 *69001.7]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=402] is closed.
[2019-03-21 17:28:37 *69001.7]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=394] is closed.
[2019-03-21 17:28:37 *69001.7]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=410] is closed.
[2019-03-21 17:28:37 *69000.6]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=489] is closed.
[2019-03-21 17:28:37 *69001.7]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=450] is closed.
[2019-03-21 17:28:37 *69001.7]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=426] is closed.
[2019-03-21 17:28:37 *69001.7]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=418] is closed.
[2019-03-21 17:28:37 *69001.7]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=434] is closed.
[2019-03-21 17:28:37 *69001.7]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=482] is closed.
[2019-03-21 17:28:37 *69001.7]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=442] is closed.
[2019-03-21 17:28:37 *69001.7]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=466] is closed.
[2019-03-21 17:28:37 *69001.7]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=458] is closed.
[2019-03-21 17:28:37 *69001.7]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=474] is closed.
[2019-03-21 17:28:37 *69001.7]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=514] is closed.
[2019-03-21 17:28:37 *69001.7]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=490] is closed.
[2019-03-21 17:28:37 *69001.7]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=498] is closed.
[2019-03-21 17:28:37 *69001.7]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 348 byte failed, because connection[fd=506] is closed.
[2019-03-21 17:29:10 *68999.5]	NOTICE	swFactoryProcess_finish (ERROR 1005): connection[fd=3770] does not exists.
[2019-03-21 17:29:10 *68998.4]	NOTICE	swFactoryProcess_finish (ERROR 1005): connection[fd=3769] does not exists.
[2019-03-21 17:29:10 *68997.3]	NOTICE	swFactoryProcess_finish (ERROR 1005): connection[fd=3768] does not exists.
[2019-03-21 17:29:10 *68997.3]	NOTICE	swFactoryProcess_finish (ERROR 1005): connection[fd=3789] does not exists.
[2019-03-21 17:29:10 *69000.6]	NOTICE	swFactoryProcess_finish (ERROR 1005): connection[fd=3792] does not exists.
[2019-03-21 17:29:10 *68995.1]	NOTICE	swFactoryProcess_finish (ERROR 1005): connection[fd=3795] does not exists.
[2019-03-21 17:29:10 *68996.2]	NOTICE	swFactoryProcess_finish (ERROR 1005): connection[fd=3782] does not exists.
[2019-03-21 17:29:10 *68995.1]	NOTICE	swFactoryProcess_finish (ERROR 1005): connection[fd=3774] does not exists.
[2019-03-21 17:29:10 *68996.2]	NOTICE	swFactoryProcess_finish (ERROR 1005): connection[fd=3775] does not exists.
[2019-03-21 17:29:10 *68995.1]	NOTICE	swFactoryProcess_finish (ERROR 1005): connection[fd=3781] does not exists.
[2019-03-21 17:29:10 *69000.6]	NOTICE	swFactoryProcess_finish (ERROR 1005): connection[fd=3784] does not exists.
[2019-03-21 17:29:10 *68999.5]	NOTICE	swFactoryProcess_finish (ERROR 1005): connection[fd=3777] does not exists.
[2019-03-21 17:29:10 *68996.2]	NOTICE	swFactoryProcess_finish (ERROR 1005): connection[fd=3804] does not exists.
[2019-03-21 17:29:10 *69000.6]	NOTICE	swFactoryProcess_finish (ERROR 1005): connection[fd=3778] does not exists.
[2019-03-21 17:29:10 *68999.5]	NOTICE	swFactoryProcess_finish (ERROR 1005): connection[fd=3783] does not exists.
[2019-03-21 17:29:10 *69000.6]	NOTICE	swFactoryProcess_finish (ERROR 1005): connection[fd=3771] does not exists.
[2019-03-21 17:29:10 *68996.2]	NOTICE	swFactoryProcess_finish (ERROR 1005): connection[fd=3788] does not exists.
[2019-03-21 17:29:10 *68994.0]	NOTICE	swFactoryProcess_finish (ERROR 1005): connection[fd=3794] does not exists.
[2019-03-21 17:29:10 *68998.4]	NOTICE	swFactoryProcess_finish (ERROR 1005): connection[fd=3790] does not exists.
[2019-03-21 17:29:10 *68994.0]	NOTICE	swFactoryProcess_finish (ERROR 1005): connection[fd=3780] does not exists.
[2019-03-21 17:29:10 *69001.7]	NOTICE	swFactoryProcess_finish (ERROR 1005): connection[fd=3793] does not exists.
[2019-03-21 17:29:10 *68994.0]	NOTICE	swFactoryProcess_finish (ERROR 1005): connection[fd=3773] does not exists.
[2019-03-21 17:29:10 *68997.3]	NOTICE	swFactoryProcess_finish (ERROR 1005): connection[fd=3776] does not exists.
[2019-03-21 17:29:10 *69001.7]	NOTICE	swFactoryProcess_finish (ERROR 1005): connection[fd=3785] does not exists.
[2019-03-21 17:29:10 *69001.7]	NOTICE	swFactoryProcess_finish (ERROR 1005): connection[fd=3779] does not exists.
[2019-03-21 17:29:10 *68997.3]	NOTICE	swFactoryProcess_finish (ERROR 1005): connection[fd=3821] does not exists.
[2019-03-21 17:29:10 *68995.1]	NOTICE	swFactoryProcess_finish (ERROR 1005): connection[fd=3803] does not exists.
[2019-03-21 17:29:10 *69001.7]	NOTICE	swFactoryProcess_finish (ERROR 1005): connection[fd=3772] does not exists.
[2019-03-21 17:29:10 *68996.2]	NOTICE	swFactoryProcess_finish (ERROR 1005): connection[fd=3796] does not exists.
[2019-03-21 17:29:10 *69000.6]	NOTICE	swFactoryProcess_finish (ERROR 1005): connection[fd=3816] does not exists.
[2019-03-21 17:29:10 *68999.5]	NOTICE	swFactoryProcess_finish (ERROR 1005): connection[fd=3791] does not exists.
[2019-03-21 17:29:10 *68995.1]	NOTICE	swFactoryProcess_finish (ERROR 1005): connection[fd=3787] does not exists.
[2019-03-21 17:29:10 *68999.5]	NOTICE	swFactoryProcess_finish (ERROR 1005): connection[fd=3815] does not exists.
[2019-03-21 17:29:10 *68994.0]	NOTICE	swFactoryProcess_finish (ERROR 1005): connection[fd=3802] does not exists.
[2019-03-21 17:29:10 *69000.6]	NOTICE	swFactoryProcess_finish (ERROR 1005): connection[fd=3800] does not exists.
[2019-03-21 17:29:10 *68998.4]	NOTICE	swFactoryProcess_finish (ERROR 1005): connection[fd=3814] does not exists.
[2019-03-21 17:29:10 *69001.7]	NOTICE	swFactoryProcess_finish (ERROR 1005): connection[fd=3801] does not exists.
[2019-03-21 17:29:10 *68994.0]	NOTICE	swFactoryProcess_finish (ERROR 1005): connection[fd=3786] does not exists.
[2019-03-21 17:29:10 *68999.5]	NOTICE	swFactoryProcess_finish (ERROR 1005): connection[fd=3799] does not exists.
[2019-03-21 17:29:10 *68998.4]	NOTICE	swFactoryProcess_finish (ERROR 1005): connection[fd=3798] does not exists.
[2019-03-21 17:29:10 *68997.3]	NOTICE	swFactoryProcess_finish (ERROR 1005): connection[fd=3797] does not exists.
[2019-03-21 17:29:10 *68996.2]	NOTICE	swFactoryProcess_finish (ERROR 1005): connection[fd=3820] does not exists.
[2019-03-21 17:29:10 *68995.1]	NOTICE	swFactoryProcess_finish (ERROR 1005): connection[fd=3819] does not exists.
[2019-03-21 17:29:10 *68996.2]	NOTICE	swFactoryProcess_finish (ERROR 1005): connection[fd=3812] does not exists.
[2019-03-21 17:29:10 *68994.0]	NOTICE	swFactoryProcess_finish (ERROR 1005): connection[fd=3810] does not exists.
[2019-03-21 17:29:10 *68995.1]	NOTICE	swFactoryProcess_finish (ERROR 1005): connection[fd=3811] does not exists.
[2019-03-21 17:29:10 *69000.6]	NOTICE	swFactoryProcess_finish (ERROR 1005): connection[fd=3824] does not exists.
[2019-03-21 17:29:10 *69001.7]	NOTICE	swFactoryProcess_finish (ERROR 1005): connection[fd=3825] does not exists.
[2019-03-21 17:29:10 *69000.6]	NOTICE	swFactoryProcess_finish (ERROR 1005): connection[fd=3808] does not exists.
[2019-03-21 17:29:10 *68997.3]	NOTICE	swFactoryProcess_finish (ERROR 1005): connection[fd=3813] does not exists.
[2019-03-21 17:29:10 *69001.7]	NOTICE	swFactoryProcess_finish (ERROR 1005): connection[fd=3809] does not exists.
[2019-03-21 17:29:10 *69001.7]	NOTICE	swFactoryProcess_finish (ERROR 1005): connection[fd=3817] does not exists.
[2019-03-21 17:29:10 *68999.5]	NOTICE	swFactoryProcess_finish (ERROR 1005): connection[fd=3807] does not exists.
[2019-03-21 17:29:10 *68994.0]	NOTICE	swFactoryProcess_finish (ERROR 1005): connection[fd=3826] does not exists.
[2019-03-21 17:29:10 *68997.3]	NOTICE	swFactoryProcess_finish (ERROR 1005): connection[fd=3805] does not exists.
[2019-03-21 17:29:10 *68999.5]	NOTICE	swFactoryProcess_finish (ERROR 1005): connection[fd=3823] does not exists.
[2019-03-21 17:29:10 *69000.6]	NOTICE	swFactoryProcess_finish (ERROR 1005): connection[fd=3846] does not exists.
[2019-03-21 17:29:10 *68999.5]	NOTICE	swFactoryProcess_finish (ERROR 1005): connection[fd=3839] does not exists.
[2019-03-21 17:29:10 *68995.1]	NOTICE	swFactoryProcess_finish (ERROR 1005): connection[fd=3842] does not exists.
[2019-03-21 17:29:10 *69000.6]	NOTICE	swFactoryProcess_finish (ERROR 1005): connection[fd=3840] does not exists.
[2019-03-21 17:29:10 *68994.0]	NOTICE	swFactoryProcess_finish (ERROR 1005): connection[fd=3818] does not exists.
[2019-03-21 17:29:10 *68998.4]	NOTICE	swFactoryProcess_finish (ERROR 1005): connection[fd=3806] does not exists.
[2019-03-21 17:29:10 *68997.3]	NOTICE	swFactoryProcess_finish (ERROR 1005): connection[fd=3834] does not exists.
[2019-03-21 17:29:10 *68999.5]	NOTICE	swFactoryProcess_finish (ERROR 1005): connection[fd=3831] does not exists.
[2019-03-21 17:29:10 *69000.6]	NOTICE	swFactoryProcess_finish (ERROR 1005): connection[fd=3862] does not exists.
[2019-03-21 17:29:10 *68998.4]	NOTICE	swFactoryProcess_finish (ERROR 1005): connection[fd=3822] does not exists.
[2019-03-21 17:29:10 *68997.3]	NOTICE	swFactoryProcess_finish (ERROR 1005): connection[fd=3829] does not exists.
[2019-03-21 17:29:10 *69000.6]	NOTICE	swFactoryProcess_finish (ERROR 1005): connection[fd=3854] does not exists.
[2019-03-21 17:29:10 *68998.4]	NOTICE	swFactoryProcess_finish (ERROR 1005): connection[fd=3835] does not exists.
[2019-03-21 17:29:10 *68999.5]	NOTICE	swFactoryProcess_finish (ERROR 1005): connection[fd=3845] does not exists.
[2019-03-21 17:29:10 *68997.3]	NOTICE	swFactoryProcess_finish (ERROR 1005): connection[fd=3851] does not exists.
[2019-03-21 17:29:10 *68996.2]	NOTICE	swFactoryProcess_finish (ERROR 1005): connection[fd=3866] does not exists.
[2019-03-21 17:29:10 *68999.5]	NOTICE	swFactoryProcess_finish (ERROR 1005): connection[fd=3853] does not exists.
[2019-03-21 17:29:10 *69001.7]	NOTICE	swFactoryProcess_finish (ERROR 1005): connection[fd=3863] does not exists.
[2019-03-21 17:29:10 *68997.3]	NOTICE	swFactoryProcess_finish (ERROR 1005): connection[fd=3867] does not exists.
[2019-03-21 17:29:10 *68998.4]	NOTICE	swFactoryProcess_finish (ERROR 1005): connection[fd=3836] does not exists.
[2019-03-21 17:29:10 *68996.2]	NOTICE	swFactoryProcess_finish (ERROR 1005): connection[fd=3843] does not exists.
[2019-03-21 17:29:10 *69001.7]	NOTICE	swFactoryProcess_finish (ERROR 1005): connection[fd=3832] does not exists.
[2019-03-21 17:29:10 *68995.1]	NOTICE	swFactoryProcess_finish (ERROR 1005): connection[fd=3849] does not exists.
[2019-03-21 17:29:10 *68998.4]	NOTICE	swFactoryProcess_finish (ERROR 1005): connection[fd=3838] does not exists.
[2019-03-21 17:29:10 *68999.5]	NOTICE	swFactoryProcess_finish (ERROR 1005): connection[fd=3861] does not exists.
[2019-03-21 17:29:10 *68995.1]	NOTICE	swFactoryProcess_finish (ERROR 1005): connection[fd=3865] does not exists.
[2019-03-21 17:29:10 *68996.2]	NOTICE	swFactoryProcess_finish (ERROR 1005): connection[fd=3850] does not exists.
[2019-03-21 17:29:10 *68994.0]	NOTICE	swFactoryProcess_finish (ERROR 1005): connection[fd=3856] does not exists.
[2019-03-21 17:29:10 *68998.4]	NOTICE	swFactoryProcess_finish (ERROR 1005): connection[fd=3830] does not exists.
[2019-03-21 17:29:10 *68995.1]	NOTICE	swFactoryProcess_finish (ERROR 1005): connection[fd=3827] does not exists.
[2019-03-21 17:29:10 *68996.2]	NOTICE	swFactoryProcess_finish (ERROR 1005): connection[fd=3828] does not exists.
[2019-03-21 17:29:10 *68994.0]	NOTICE	swFactoryProcess_finish (ERROR 1005): connection[fd=3864] does not exists.
[2019-03-21 17:29:10 *69001.7]	NOTICE	swFactoryProcess_finish (ERROR 1005): connection[fd=3847] does not exists.
[2019-03-21 17:29:10 *68996.2]	NOTICE	swFactoryProcess_finish (ERROR 1005): connection[fd=3837] does not exists.
[2019-03-21 17:29:10 *68997.3]	NOTICE	swFactoryProcess_finish (ERROR 1005): connection[fd=3859] does not exists.
[2019-03-21 17:29:10 *68994.0]	NOTICE	swFactoryProcess_finish (ERROR 1005): connection[fd=3848] does not exists.
[2019-03-21 17:29:10 *69001.7]	NOTICE	swFactoryProcess_finish (ERROR 1005): connection[fd=3855] does not exists.
[2019-03-21 17:29:10 *68998.4]	NOTICE	swFactoryProcess_finish (ERROR 1005): connection[fd=3844] does not exists.
[2019-03-21 17:29:10 *68996.2]	NOTICE	swFactoryProcess_finish (ERROR 1005): connection[fd=3858] does not exists.
[2019-03-21 17:29:10 *68994.0]	NOTICE	swFactoryProcess_finish (ERROR 1005): connection[fd=3833] does not exists.
[2019-03-21 17:29:10 *68995.1]	NOTICE	swFactoryProcess_finish (ERROR 1005): connection[fd=3857] does not exists.
[2019-03-21 17:29:10 *68998.4]	NOTICE	swFactoryProcess_finish (ERROR 1005): connection[fd=3852] does not exists.
[2019-03-21 17:29:10 *68994.0]	NOTICE	swFactoryProcess_finish (ERROR 1005): connection[fd=3841] does not exists.
[2019-03-21 17:29:10 *68998.4]	NOTICE	swFactoryProcess_finish (ERROR 1005): connection[fd=3860] does not exists.
[2019-03-21 17:29:10 *68998.4]	NOTICE	swFactoryProcess_finish (ERROR 1005): connection[fd=3868] does not exists.
[2019-03-21 17:30:00 *68994.0]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4090] is closed.
[2019-03-21 17:30:00 *69001.7]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4025] is closed.
[2019-03-21 17:30:00 *68995.1]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4075] is closed.
[2019-03-21 17:30:00 *69000.6]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4024] is closed.
[2019-03-21 17:30:00 *68994.0]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4098] is closed.
[2019-03-21 17:30:00 *68995.1]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4059] is closed.
[2019-03-21 17:30:00 *69000.6]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4032] is closed.
[2019-03-21 17:30:00 *69001.7]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4049] is closed.
[2019-03-21 17:30:00 *68994.0]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4074] is closed.
[2019-03-21 17:30:00 *68995.1]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4027] is closed.
[2019-03-21 17:30:00 *68994.0]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4018] is closed.
[2019-03-21 17:30:00 *69001.7]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4065] is closed.
[2019-03-21 17:30:00 *69000.6]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4072] is closed.
[2019-03-21 17:30:00 *68998.4]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4054] is closed.
[2019-03-21 17:30:00 *68995.1]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4083] is closed.
[2019-03-21 17:30:00 *69001.7]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4073] is closed.
[2019-03-21 17:30:00 *68994.0]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4002] is closed.
[2019-03-21 17:30:00 *69000.6]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4048] is closed.
[2019-03-21 17:30:00 *69001.7]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4057] is closed.
[2019-03-21 17:30:00 *68995.1]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4019] is closed.
[2019-03-21 17:30:00 *68998.4]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4070] is closed.
[2019-03-21 17:30:00 *69000.6]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4088] is closed.
[2019-03-21 17:30:00 *68995.1]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4091] is closed.
[2019-03-21 17:30:00 *68998.4]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4078] is closed.
[2019-03-21 17:30:00 *69000.6]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4040] is closed.
[2019-03-21 17:30:00 *68995.1]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4003] is closed.
[2019-03-21 17:30:00 *68996.2]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4084] is closed.
[2019-03-21 17:30:00 *69000.6]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4008] is closed.
[2019-03-21 17:30:00 *68995.1]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4035] is closed.
[2019-03-21 17:30:00 *68998.4]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4094] is closed.
[2019-03-21 17:30:00 *68996.2]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4020] is closed.
[2019-03-21 17:30:00 *68995.1]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4067] is closed.
[2019-03-21 17:30:00 *68998.4]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4086] is closed.
[2019-03-21 17:30:00 *68999.5]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4063] is closed.
[2019-03-21 17:30:00 *68995.1]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4099] is closed.
[2019-03-21 17:30:00 *68998.4]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4022] is closed.
[2019-03-21 17:30:00 *68996.2]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4092] is closed.
[2019-03-21 17:30:00 *68999.5]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4071] is closed.
[2019-03-21 17:30:00 *68998.4]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4062] is closed.
[2019-03-21 17:30:00 *68997.3]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4061] is closed.
[2019-03-21 17:30:00 *68996.2]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4036] is closed.
[2019-03-21 17:30:00 *68999.5]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4007] is closed.
[2019-03-21 17:30:00 *68998.4]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4038] is closed.
[2019-03-21 17:30:00 *68996.2]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4052] is closed.
[2019-03-21 17:30:00 *68997.3]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4077] is closed.
[2019-03-21 17:30:00 *68998.4]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4030] is closed.
[2019-03-21 17:30:00 *68999.5]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4079] is closed.
[2019-03-21 17:30:00 *68996.2]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4028] is closed.
[2019-03-21 17:30:00 *68997.3]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4045] is closed.
[2019-03-21 17:30:00 *68998.4]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4046] is closed.
[2019-03-21 17:30:00 *68999.5]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4015] is closed.
[2019-03-21 17:30:00 *68996.2]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4004] is closed.
[2019-03-21 17:30:00 *68998.4]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4006] is closed.
[2019-03-21 17:30:00 *68997.3]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4029] is closed.
[2019-03-21 17:30:00 *68999.5]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4023] is closed.
[2019-03-21 17:30:00 *68998.4]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4014] is closed.
[2019-03-21 17:30:00 *68996.2]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4076] is closed.
[2019-03-21 17:30:00 *68999.5]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4039] is closed.
[2019-03-21 17:30:00 *68997.3]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4053] is closed.
[2019-03-21 17:30:00 *68996.2]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4012] is closed.
[2019-03-21 17:30:00 *68999.5]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4031] is closed.
[2019-03-21 17:30:00 *68997.3]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4005] is closed.
[2019-03-21 17:30:00 *68996.2]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4060] is closed.
[2019-03-21 17:30:00 *68999.5]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4047] is closed.
[2019-03-21 17:30:00 *68997.3]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4013] is closed.
[2019-03-21 17:30:00 *68996.2]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4044] is closed.
[2019-03-21 17:30:00 *68999.5]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4055] is closed.
[2019-03-21 17:30:00 *68997.3]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4069] is closed.
[2019-03-21 17:30:00 *68996.2]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4068] is closed.
[2019-03-21 17:30:00 *68999.5]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4087] is closed.
[2019-03-21 17:30:00 *68997.3]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4085] is closed.
[2019-03-21 17:30:00 *68999.5]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4095] is closed.
[2019-03-21 17:30:00 *68997.3]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4093] is closed.
[2019-03-21 17:30:00 *68997.3]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4021] is closed.
[2019-03-21 17:30:00 *68997.3]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4037] is closed.
[2019-03-21 17:30:29 *69001.7]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4166] is closed.
[2019-03-21 17:30:29 *68996.2]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4169] is closed.
[2019-03-21 17:30:29 *68995.1]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4176] is closed.
[2019-03-21 17:30:29 *68999.5]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4172] is closed.
[2019-03-21 17:30:29 *68998.4]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4123] is closed.
[2019-03-21 17:30:29 *68994.0]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4199] is closed.
[2019-03-21 17:30:29 *68995.1]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4152] is closed.
[2019-03-21 17:30:29 *68999.5]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4108] is closed.
[2019-03-21 17:30:29 *69001.7]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4142] is closed.
[2019-03-21 17:30:29 *68998.4]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4195] is closed.
[2019-03-21 17:30:29 *68996.2]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4145] is closed.
[2019-03-21 17:30:29 *68994.0]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4143] is closed.
[2019-03-21 17:30:29 *68995.1]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4184] is closed.
[2019-03-21 17:30:29 *68998.4]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4147] is closed.
[2019-03-21 17:30:29 *68994.0]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4127] is closed.
[2019-03-21 17:30:29 *68999.5]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4116] is closed.
[2019-03-21 17:30:29 *68995.1]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4104] is closed.
[2019-03-21 17:30:29 *68998.4]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4163] is closed.
[2019-03-21 17:30:29 *68994.0]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4103] is closed.
[2019-03-21 17:30:29 *68999.5]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4180] is closed.
[2019-03-21 17:30:29 *68995.1]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4112] is closed.
[2019-03-21 17:30:29 *68998.4]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4171] is closed.
[2019-03-21 17:30:29 *68994.0]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4135] is closed.
[2019-03-21 17:30:29 *68996.2]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4153] is closed.
[2019-03-21 17:30:29 *68995.1]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4192] is closed.
[2019-03-21 17:30:29 *68998.4]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4179] is closed.
[2019-03-21 17:30:29 *69000.6]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4157] is closed.
[2019-03-21 17:30:29 *68996.2]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4129] is closed.
[2019-03-21 17:30:29 *68995.1]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4200] is closed.
[2019-03-21 17:30:29 *68997.3]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4146] is closed.
[2019-03-21 17:30:29 *68994.0]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4167] is closed.
[2019-03-21 17:30:29 *69001.7]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4174] is closed.
[2019-03-21 17:30:29 *69000.6]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4101] is closed.
[2019-03-21 17:30:29 *68999.5]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4164] is closed.
[2019-03-21 17:30:29 *68995.1]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4120] is closed.
[2019-03-21 17:30:29 *69001.7]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4182] is closed.
[2019-03-21 17:30:29 *68994.0]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4159] is closed.
[2019-03-21 17:30:29 *68997.3]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4154] is closed.
[2019-03-21 17:30:29 *69000.6]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4181] is closed.
[2019-03-21 17:30:29 *68995.1]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4128] is closed.
[2019-03-21 17:30:29 *69001.7]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4158] is closed.
[2019-03-21 17:30:29 *68994.0]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4175] is closed.
[2019-03-21 17:30:29 *68999.5]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4124] is closed.
[2019-03-21 17:30:29 *69000.6]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4189] is closed.
[2019-03-21 17:30:29 *69001.7]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4190] is closed.
[2019-03-21 17:30:29 *68997.3]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4162] is closed.
[2019-03-21 17:30:29 *68994.0]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4119] is closed.
[2019-03-21 17:30:29 *68999.5]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4188] is closed.
[2019-03-21 17:30:29 *69001.7]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4198] is closed.
[2019-03-21 17:30:29 *69000.6]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4197] is closed.
[2019-03-21 17:30:29 *68994.0]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4151] is closed.
[2019-03-21 17:30:29 *68999.5]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4132] is closed.
[2019-03-21 17:30:29 *68997.3]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4170] is closed.
[2019-03-21 17:30:29 *69000.6]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4133] is closed.
[2019-03-21 17:30:29 *68999.5]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4148] is closed.
[2019-03-21 17:30:29 *68997.3]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4106] is closed.
[2019-03-21 17:30:29 *69000.6]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4165] is closed.
[2019-03-21 17:30:29 *68999.5]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4140] is closed.
[2019-03-21 17:30:29 *68997.3]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4178] is closed.
[2019-03-21 17:30:29 *69000.6]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4141] is closed.
[2019-03-21 17:30:29 *68999.5]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4156] is closed.
[2019-03-21 17:30:29 *68997.3]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4114] is closed.
[2019-03-21 17:30:29 *69000.6]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4173] is closed.
[2019-03-21 17:30:29 *68999.5]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4196] is closed.
[2019-03-21 17:30:29 *68997.3]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4122] is closed.
[2019-03-21 17:30:29 *69000.6]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4149] is closed.
[2019-03-21 17:30:29 *68997.3]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4186] is closed.
[2019-03-21 17:30:29 *69000.6]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4109] is closed.
[2019-03-21 17:30:29 *68997.3]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4138] is closed.
[2019-03-21 17:30:29 *69000.6]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4117] is closed.
[2019-03-21 17:30:29 *68997.3]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4194] is closed.
[2019-03-21 17:30:29 *69000.6]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4125] is closed.
[2019-03-21 17:30:29 *68997.3]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4130] is closed.
[2019-03-21 17:30:44 *68998.4]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4400] is closed.
[2019-03-21 17:30:44 *68995.1]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4381] is closed.
[2019-03-21 17:30:44 *69001.7]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4371] is closed.
[2019-03-21 17:30:44 *68998.4]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4240] is closed.
[2019-03-21 17:30:44 *68995.1]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4269] is closed.
[2019-03-21 17:30:44 *69001.7]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4379] is closed.
[2019-03-21 17:30:44 *68996.2]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4214] is closed.
[2019-03-21 17:30:44 *68998.4]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4384] is closed.
[2019-03-21 17:30:44 *68995.1]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4245] is closed.
[2019-03-21 17:30:44 *69001.7]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4395] is closed.
[2019-03-21 17:30:44 *68996.2]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4318] is closed.
[2019-03-21 17:30:44 *68998.4]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4248] is closed.
[2019-03-21 17:30:44 *68995.1]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4253] is closed.
[2019-03-21 17:30:44 *69001.7]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4243] is closed.
[2019-03-21 17:30:44 *68996.2]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4326] is closed.
[2019-03-21 17:30:44 *68998.4]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4256] is closed.
[2019-03-21 17:30:44 *69001.7]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4259] is closed.
[2019-03-21 17:30:44 *68995.1]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4261] is closed.
[2019-03-21 17:30:44 *68996.2]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4206] is closed.
[2019-03-21 17:30:44 *68998.4]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4264] is closed.
[2019-03-21 17:30:44 *69001.7]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4387] is closed.
[2019-03-21 17:30:44 *68995.1]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4285] is closed.
[2019-03-21 17:30:44 *68996.2]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4222] is closed.
[2019-03-21 17:30:44 *68998.4]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4288] is closed.
[2019-03-21 17:30:44 *69001.7]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4227] is closed.
[2019-03-21 17:30:44 *68995.1]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4277] is closed.
[2019-03-21 17:30:44 *68998.4]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4272] is closed.
[2019-03-21 17:30:44 *69001.7]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4251] is closed.
[2019-03-21 17:30:44 *68996.2]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4230] is closed.
[2019-03-21 17:30:44 *68995.1]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4293] is closed.
[2019-03-21 17:30:44 *68998.4]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4280] is closed.
[2019-03-21 17:30:44 *69001.7]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4267] is closed.
[2019-03-21 17:30:44 *68996.2]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4334] is closed.
[2019-03-21 17:30:44 *68995.1]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4309] is closed.
[2019-03-21 17:30:44 *68998.4]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4304] is closed.
[2019-03-21 17:30:44 *68996.2]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4342] is closed.
[2019-03-21 17:30:44 *68995.1]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4317] is closed.
[2019-03-21 17:30:44 *68997.3]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4391] is closed.
[2019-03-21 17:30:44 *68998.4]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4296] is closed.
[2019-03-21 17:30:44 *69001.7]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4299] is closed.
[2019-03-21 17:30:44 *68994.0]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4348] is closed.
[2019-03-21 17:30:44 *68997.3]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4247] is closed.
[2019-03-21 17:30:44 *68995.1]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4301] is closed.
[2019-03-21 17:30:44 *69001.7]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4235] is closed.
[2019-03-21 17:30:44 *68996.2]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4350] is closed.
[2019-03-21 17:30:44 *68994.0]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4356] is closed.
[2019-03-21 17:30:44 *68995.1]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4325] is closed.
[2019-03-21 17:30:44 *69001.7]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4275] is closed.
[2019-03-21 17:30:44 *68995.1]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4205] is closed.
[2019-03-21 17:30:44 *68998.4]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4312] is closed.
[2019-03-21 17:30:44 *68995.1]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4213] is closed.
[2019-03-21 17:30:44 *68998.4]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4320] is closed.
[2019-03-21 17:30:44 *68996.2]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4358] is closed.
[2019-03-21 17:30:44 *68995.1]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4349] is closed.
[2019-03-21 17:30:44 *69001.7]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4283] is closed.
[2019-03-21 17:30:44 *68994.0]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4396] is closed.
[2019-03-21 17:30:44 *68997.3]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4239] is closed.
[2019-03-21 17:30:44 *68996.2]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4382] is closed.
[2019-03-21 17:30:44 *69001.7]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4291] is closed.
[2019-03-21 17:30:44 *68998.4]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4208] is closed.
[2019-03-21 17:30:44 *68996.2]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4374] is closed.
[2019-03-21 17:30:44 *68998.4]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4216] is closed.
[2019-03-21 17:30:44 *69001.7]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4203] is closed.
[2019-03-21 17:30:44 *68996.2]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4366] is closed.
[2019-03-21 17:30:44 *68994.0]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4244] is closed.
[2019-03-21 17:30:44 *69000.6]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4258] is closed.
[2019-03-21 17:30:44 *68997.3]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4255] is closed.
[2019-03-21 17:30:44 *69001.7]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4315] is closed.
[2019-03-21 17:30:44 *68996.2]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4238] is closed.
[2019-03-21 17:30:44 *68997.3]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4271] is closed.
[2019-03-21 17:30:44 *68994.0]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4388] is closed.
[2019-03-21 17:30:44 *68996.2]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4246] is closed.
[2019-03-21 17:30:44 *69000.6]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4250] is closed.
[2019-03-21 17:30:44 *68994.0]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4364] is closed.
[2019-03-21 17:30:44 *68997.3]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4263] is closed.
[2019-03-21 17:30:44 *68996.2]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4390] is closed.
[2019-03-21 17:30:44 *68994.0]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4372] is closed.
[2019-03-21 17:30:44 *69000.6]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4274] is closed.
[2019-03-21 17:30:44 *68997.3]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4279] is closed.
[2019-03-21 17:30:44 *68996.2]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4398] is closed.
[2019-03-21 17:30:44 *68994.0]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4380] is closed.
[2019-03-21 17:30:44 *68997.3]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4303] is closed.
[2019-03-21 17:30:44 *69000.6]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4282] is closed.
[2019-03-21 17:30:44 *68996.2]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4278] is closed.
[2019-03-21 17:30:44 *68994.0]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4236] is closed.
[2019-03-21 17:30:44 *68997.3]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4295] is closed.
[2019-03-21 17:30:44 *69000.6]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4266] is closed.
[2019-03-21 17:30:44 *68996.2]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4270] is closed.
[2019-03-21 17:30:44 *68994.0]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4228] is closed.
[2019-03-21 17:30:44 *68997.3]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4207] is closed.
[2019-03-21 17:30:44 *69000.6]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4290] is closed.
[2019-03-21 17:30:44 *68996.2]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4254] is closed.
[2019-03-21 17:30:44 *68994.0]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4252] is closed.
[2019-03-21 17:30:44 *69000.6]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4210] is closed.
[2019-03-21 17:30:44 *68999.5]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4345] is closed.
[2019-03-21 17:30:44 *68996.2]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4294] is closed.
[2019-03-21 17:30:44 *68997.3]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4287] is closed.
[2019-03-21 17:30:44 *68994.0]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4260] is closed.
[2019-03-21 17:30:44 *68997.3]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4319] is closed.
[2019-03-21 17:30:44 *68994.0]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4268] is closed.
[2019-03-21 17:30:44 *69000.6]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4314] is closed.
[2019-03-21 17:30:44 *68999.5]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4353] is closed.
[2019-03-21 17:30:44 *68994.0]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4284] is closed.
[2019-03-21 17:30:44 *68997.3]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4215] is closed.
[2019-03-21 17:30:44 *68994.0]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4300] is closed.
[2019-03-21 17:30:44 *69000.6]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4298] is closed.
[2019-03-21 17:30:44 *68997.3]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4311] is closed.
[2019-03-21 17:30:44 *68999.5]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4377] is closed.
[2019-03-21 17:30:44 *68994.0]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4292] is closed.
[2019-03-21 17:30:44 *69000.6]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4218] is closed.
[2019-03-21 17:30:44 *68997.3]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4343] is closed.
[2019-03-21 17:30:44 *68999.5]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4393] is closed.
[2019-03-21 17:30:44 *68994.0]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4276] is closed.
[2019-03-21 17:30:44 *69000.6]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4306] is closed.
[2019-03-21 17:30:44 *68997.3]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4327] is closed.
[2019-03-21 17:30:44 *68999.5]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4385] is closed.
[2019-03-21 17:30:44 *68994.0]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4308] is closed.
[2019-03-21 17:30:44 *69000.6]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4226] is closed.
[2019-03-21 17:30:44 *68997.3]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4359] is closed.
[2019-03-21 17:30:44 *68999.5]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4401] is closed.
[2019-03-21 17:30:44 *68994.0]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4204] is closed.
[2019-03-21 17:30:44 *69000.6]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4330] is closed.
[2019-03-21 17:30:44 *68997.3]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4335] is closed.
[2019-03-21 17:30:44 *68999.5]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4209] is closed.
[2019-03-21 17:30:44 *68994.0]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4316] is closed.
[2019-03-21 17:30:44 *69000.6]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4322] is closed.
[2019-03-21 17:30:44 *68997.3]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4223] is closed.
[2019-03-21 17:30:44 *68994.0]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4212] is closed.
[2019-03-21 17:30:44 *68999.5]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4249] is closed.
[2019-03-21 17:30:44 *69000.6]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4202] is closed.
[2019-03-21 17:30:44 *68997.3]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4375] is closed.
[2019-03-21 17:30:44 *68994.0]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4324] is closed.
[2019-03-21 17:30:44 *68999.5]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4233] is closed.
[2019-03-21 17:30:44 *69000.6]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4338] is closed.
[2019-03-21 17:30:44 *68997.3]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4351] is closed.
[2019-03-21 17:30:44 *68994.0]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4340] is closed.
[2019-03-21 17:30:44 *68999.5]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4241] is closed.
[2019-03-21 17:30:44 *68997.3]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4383] is closed.
[2019-03-21 17:30:44 *69000.6]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4354] is closed.
[2019-03-21 17:30:44 *68994.0]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4220] is closed.
[2019-03-21 17:30:44 *68999.5]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4265] is closed.
[2019-03-21 17:30:44 *68997.3]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4231] is closed.
[2019-03-21 17:30:44 *69000.6]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4346] is closed.
[2019-03-21 17:30:44 *68994.0]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4332] is closed.
[2019-03-21 17:30:44 *68999.5]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4257] is closed.
[2019-03-21 17:30:44 *68997.3]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4367] is closed.
[2019-03-21 17:30:44 *69000.6]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4370] is closed.
[2019-03-21 17:30:44 *68999.5]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4281] is closed.
[2019-03-21 17:30:44 *68997.3]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4399] is closed.
[2019-03-21 17:30:44 *69000.6]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4362] is closed.
[2019-03-21 17:30:44 *68999.5]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4289] is closed.
[2019-03-21 17:30:44 *69000.6]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4378] is closed.
[2019-03-21 17:30:44 *68999.5]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4273] is closed.
[2019-03-21 17:30:44 *69000.6]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4394] is closed.
[2019-03-21 17:30:44 *68999.5]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4297] is closed.
[2019-03-21 17:30:44 *69000.6]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4234] is closed.
[2019-03-21 17:30:44 *69000.6]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4386] is closed.
[2019-03-21 17:30:44 *68999.5]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4305] is closed.
[2019-03-21 17:30:44 *69000.6]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4242] is closed.
[2019-03-21 17:30:44 *68999.5]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4313] is closed.
[2019-03-21 17:30:44 *68999.5]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4321] is closed.
[2019-03-21 17:30:44 *68999.5]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4329] is closed.
[2019-03-21 17:30:44 *68999.5]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4361] is closed.
[2019-03-21 17:30:44 *68999.5]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4225] is closed.
[2019-03-21 17:30:44 *68999.5]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4369] is closed.
[2019-03-21 17:30:44 *68999.5]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4217] is closed.
[2019-03-21 17:30:44 *68999.5]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 248 byte failed, because connection[fd=4337] is closed.
